<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FishImg</name>
   <tag></tag>
   <elementGuidId>24da44ff-43d4-47e4-b741-46b97c749967</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SidebarContent > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@src = '../images/fish_icon.gif']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SidebarContent >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b5d83361-1e53-48b2-8275-71cf5bc0ff25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/fish_icon.gif</value>
      <webElementGuid>943d8b97-1661-4453-bcf9-7602aaf24aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SidebarContent&quot;)/a[1]/img[1]</value>
      <webElementGuid>3f988080-c77e-473a-9082-14c95d864c58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SidebarContent']/a/img</value>
      <webElementGuid>79de28ce-b892-4597-aa84-4261f45f21a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>76310419-d967-496c-a74f-8f4defe7e866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/fish_icon.gif']</value>
      <webElementGuid>968a52ca-a32d-4228-8a15-2fb20055a740</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
