<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Working with the Product Catalog</name>
   <tag></tag>
   <elementGuidId>ac1f370e-6b3a-468a-b7ca-02f8a5e6e2bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Content']/h2[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Working with the Product Catalog&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b2147e94-f675-4d67-90ce-c0ad347d4345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Working with the Product Catalog</value>
      <webElementGuid>91fd118b-84a4-4469-b9e9-33f50eac5dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Content&quot;)/h2[3]</value>
      <webElementGuid>42876182-6026-4134-85a2-8737b876dc1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Content']/h2[3]</value>
      <webElementGuid>fb6dd364-79b4-44a9-a5c1-e0049b7c268a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signing In'])[2]/following::h2[1]</value>
      <webElementGuid>09d2967d-dc67-4a97-b6ed-0a44e7337d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signing Up'])[2]/following::h2[2]</value>
      <webElementGuid>966f83d4-8299-4a4e-95f9-48d2f04f5cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browsing the Catalog'])[2]/preceding::h2[1]</value>
      <webElementGuid>6eb7aa46-acdd-4ff9-b818-3ac6db6b389c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Searching the Catalog'])[2]/preceding::h2[1]</value>
      <webElementGuid>faf77b0e-5088-4e56-bde8-629a74d088e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[3]</value>
      <webElementGuid>fb41c69b-d5d9-4078-b44c-d80c232bd652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Working with the Product Catalog' or . = 'Working with the Product Catalog')]</value>
      <webElementGuid>2c57531f-6a9f-4c08-a1aa-f56485fe76cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
