<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>username</name>
   <tag></tag>
   <elementGuidId>1fef4cb5-d3da-4237-844f-dadcfd74b546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stripes--1235341998</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#stripes--1235341998</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee10def1-c378-4748-b486-663bbf8f21c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>a1accb11-5827-4eae-aa73-12479bbd0d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stripes--1235341998</value>
      <webElementGuid>7d6cc1f3-15af-4e00-9a42-2211becfa916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71f2f841-e9c8-44bc-a61c-3e67eea2ed45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stripes--1235341998&quot;)</value>
      <webElementGuid>a01a0399-5001-4eb0-a02e-c6a5fbaa6b12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stripes--1235341998']</value>
      <webElementGuid>395be24b-b4a5-4399-a635-2bdee3b0ea15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/p[2]/input</value>
      <webElementGuid>946a7024-7b63-4226-8378-c1363fb33e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/input</value>
      <webElementGuid>407cd0af-efa8-483c-b92a-c5f485ff3f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @id = 'stripes--1235341998' and @type = 'text']</value>
      <webElementGuid>f448a5cc-46b6-44a1-a99a-371fc7d0104c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stripes-1373953574']</value>
      <webElementGuid>b5e095d8-f57f-4a1a-874c-fb55576d037e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @id = 'stripes-1373953574' and @type = 'text']</value>
      <webElementGuid>1c839c01-dfc3-4a3d-b809-d49d790c907a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
